[Service]
# This is intentional
ExecStart=
# gnome-kiosk >= 50 blocks switching to virtual console by default
# --enable-vt-switch enables that. bsc#1261932
ExecStart=/usr/bin/gnome-kiosk --enable-vt-switch
