[Service]
# We have to explicitly clear ExecStart which (most probably)
# exists in the original service file. If not systemd will try
# to start every ExecStart (original even the one added bellow)
ExecStart=
# gnome-kiosk >= 50 blocks switching to virtual console by default
# --enable-vt-switch enables that. bsc#1261932
ExecStart=/usr/bin/gnome-kiosk --enable-vt-switch
